# SPDX-FileCopyrightText: 2025 Pedrenrique G. Guimarães <admin@esportsmanager.net>
# SPDX-License-Identifier: GPL-3.0-or-later
# License-Filename: LICENSES/GPL-3.0-or-later

[project]
name = "esports-manager"
version = "0.1.0"
description = "A free and open source eSports manager game"
authors = [{ name = "sturdy-robot", email = "admin@esportsmanager.net" }]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn[standard]>=0.35.0",
    "sqlmodel>=0.0.22",
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.43",
    "pywebview[qt]>=6.0",
    "jinja2>=3.1.6",
    "pytailwindcss>=0.2.0",
    "httpx>=0.26.1",
    "pycountry>=24.6.1",
    "aiofiles>=24.1.0",
    "aiosqlite>=0.21.0",
]

[dependency-groups]
dev = ["pre-commit>=4.2.0", "pytest>=8.3.5", "ruff>=0.11.11"]
