#      eSports Manager - free and open source eSports Management game
#      Copyright (C) 2020-2023  Pedrenrique G. Guimarães
#
#      This program is free software: you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation, either version 3 of the License, or
#      (at your option) any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU General Public License for more details.
#
#      You should have received a copy of the GNU General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.
def get_default_champion_defs():
    return [
        {"name": "Aatrox", "lanes": ["TOP"]},
        {"name": "Ahri", "lanes": ["MID"]},
        {"name": "Akali", "lanes": ["TOP", "MID"]},
        {"name": "Akshan", "lanes": ["MID"]},
        {"name": "Alistar", "lanes": ["SUP"]},
        {"name": "Amumu", "lanes": ["JG"]},
        {"name": "Anivia", "lanes": ["MID"]},
        {"name": "Annie", "lanes": ["MID"]},
        {"name": "Aphelios", "lanes": ["BOT"]},
        {"name": "Ashe", "lanes": ["BOT"]},
        {"name": "Aurelion Sol", "lanes": ["MID"]},
        {"name": "Azir", "lanes": ["MID"]},
        {"name": "Bard", "lanes": ["SUP"]},
        {"name": "Bel'Veth", "lanes": ["JG"]},
        {"name": "Blitzcrank", "lanes": ["SUP"]},
        {"name": "Brand", "lanes": ["SUP"]},
        {"name": "Braum", "lanes": ["SUP"]},
        {"name": "Caitlyn", "lanes": ["BOT"]},
        {"name": "Camille", "lanes": ["TOP"]},
        {"name": "Cassiopeia", "lanes": ["MID"]},
        {"name": "Cho'Gath", "lanes": ["TOP"]},
        {"name": "Corki", "lanes": ["MID"]},
        {"name": "Darius", "lanes": ["TOP"]},
        {"name": "Diana", "lanes": ["JG", "MID"]},
        {"name": "Dr. Mundo", "lanes": ["TOP"]},
        {"name": "Draven", "lanes": ["BOT"]},
        {"name": "Ekko", "lanes": ["JG", "MID"]},
        {"name": "Elise", "lanes": ["JG"]},
        {"name": "Evelynn", "lanes": ["JG"]},
        {"name": "Ezreal", "lanes": ["BOT"]},
        {"name": "Fiddlesticks", "lanes": ["JG"]},
        {"name": "Fiora", "lanes": ["TOP"]},
        {"name": "Fizz", "lanes": ["MID"]},
        {"name": "Galio", "lanes": ["MID"]},
        {"name": "Gangplank", "lanes": ["TOP"]},
        {"name": "Garen", "lanes": ["TOP"]},
        {"name": "Gnar", "lanes": ["TOP"]},
        {"name": "Gragas", "lanes": ["JG"]},
        {"name": "Graves", "lanes": ["JG"]},
        {"name": "Gwen", "lanes": ["TOP"]},
        {"name": "Hecarim", "lanes": ["JG"]},
        {"name": "Heimerdinger", "lanes": ["MID"]},
        {"name": "Illaoi", "lanes": ["TOP"]},
        {"name": "Irelia", "lanes": ["TOP", "MID"]},
        {"name": "Ivern", "lanes": ["JG"]},
        {"name": "Janna", "lanes": ["SUP"]},
        {"name": "Jarvan IV", "lanes": ["JG"]},
        {"name": "Jax", "lanes": ["TOP", "JG"]},
        {"name": "Jayce", "lanes": ["TOP"]},
        {"name": "Jhin", "lanes": ["BOT"]},
        {"name": "Jinx", "lanes": ["BOT"]},
        {"name": "K'Sante", "lanes": ["TOP"]},
        {"name": "Kai'Sa", "lanes": ["BOT"]},
        {"name": "Kalista", "lanes": ["BOT"]},
        {"name": "Karma", "lanes": ["SUP"]},
        {"name": "Karthus", "lanes": ["JG"]},
        {"name": "Kassadin", "lanes": ["MID"]},
        {"name": "Katarina", "lanes": ["MID"]},
        {"name": "Kayle", "lanes": ["TOP"]},
        {"name": "Kayn", "lanes": ["JG"]},
        {"name": "Kennen", "lanes": ["TOP"]},
        {"name": "Kha'Zix", "lanes": ["JG"]},
        {"name": "Kindred", "lanes": ["JG"]},
        {"name": "Kled", "lanes": ["TOP"]},
        {"name": "Kog'Maw", "lanes": ["BOT"]},
        {"name": "LeBlanc", "lanes": ["MID"]},
        {"name": "Lee Sin", "lanes": ["JG"]},
        {"name": "Leona", "lanes": ["SUP"]},
        {"name": "Lillia", "lanes": ["JG"]},
        {"name": "Lissandra", "lanes": ["MID"]},
        {"name": "Lucian", "lanes": ["BOT"]},
        {"name": "Lulu", "lanes": ["SUP"]},
        {"name": "Lux", "lanes": ["MID", "SUP"]},
        {"name": "Malphite", "lanes": ["TOP", "SUP"]},
        {"name": "Malzahar", "lanes": ["MID"]},
        {"name": "Maokai", "lanes": ["TOP"]},
        {"name": "Master Yi", "lanes": ["JG"]},
        {"name": "Miss Fortune", "lanes": ["BOT"]},
        {"name": "Mordekaiser", "lanes": ["TOP"]},
        {"name": "Morgana", "lanes": ["SUP"]},
        {"name": "Nami", "lanes": ["SUP"]},
        {"name": "Nasus", "lanes": ["TOP"]},
        {"name": "Nautilus", "lanes": ["SUP"]},
        {"name": "Neeko", "lanes": ["MID"]},
        {"name": "Nidalee", "lanes": ["JG"]},
        {"name": "Nilah", "lanes": ["BOT"]},
        {"name": "Nocturne", "lanes": ["JG"]},
        {"name": "Nunu & Willump", "lanes": ["JG", "MID"]},
        {"name": "Olaf", "lanes": ["JG"]},
        {"name": "Orianna", "lanes": ["MID"]},
        {"name": "Ornn", "lanes": ["TOP"]},
        {"name": "Pantheon", "lanes": ["MID", "SUP"]},
        {"name": "Poppy", "lanes": ["TOP"]},
        {"name": "Pyke", "lanes": ["SUP"]},
        {"name": "Qiyana", "lanes": ["MID"]},
        {"name": "Quinn", "lanes": ["TOP"]},
        {"name": "Rakan", "lanes": ["SUP"]},
        {"name": "Rammus", "lanes": ["JG"]},
        {"name": "Rek'Sai", "lanes": ["JG"]},
        {"name": "Rell", "lanes": []},
        {"name": "Renata Glasc", "lanes": ["SUP"]},
        {"name": "Renekton", "lanes": ["TOP"]},
        {"name": "Rengar", "lanes": ["JG"]},
        {"name": "Riven", "lanes": ["TOP"]},
        {"name": "Rumble", "lanes": ["TOP"]},
        {"name": "Ryze", "lanes": ["MID"]},
        {"name": "Samira", "lanes": []},
        {"name": "Sejuani", "lanes": ["JG"]},
        {"name": "Senna", "lanes": ["SUP"]},
        {"name": "Seraphine", "lanes": []},
        {"name": "Sett", "lanes": ["TOP", "JG", "SUP"]},
        {"name": "Shaco", "lanes": ["JG"]},
        {"name": "Shen", "lanes": ["TOP"]},
        {"name": "Shyvana", "lanes": ["JG"]},
        {"name": "Singed", "lanes": ["TOP"]},
        {"name": "Sion", "lanes": ["TOP"]},
        {"name": "Sivir", "lanes": ["BOT"]},
        {"name": "Skarner", "lanes": ["JG"]},
        {"name": "Sona", "lanes": ["SUP"]},
        {"name": "Soraka", "lanes": ["SUP"]},
        {"name": "Swain", "lanes": ["TOP", "MID", "SUP"]},
        {"name": "Sylas", "lanes": ["MID"]},
        {"name": "Syndra", "lanes": ["MID"]},
        {"name": "Tahm Kench", "lanes": ["TOP"]},
        {"name": "Taliyah", "lanes": ["JG"]},
        {"name": "Talon", "lanes": ["MID"]},
        {"name": "Taric", "lanes": ["SUP"]},
        {"name": "Teemo", "lanes": ["TOP"]},
        {"name": "Thresh", "lanes": ["SUP"]},
        {"name": "Tristana", "lanes": ["BOT"]},
        {"name": "Trundle", "lanes": ["JG"]},
        {"name": "Tryndamere", "lanes": ["TOP"]},
        {"name": "Twisted Fate", "lanes": ["MID"]},
        {"name": "Twitch", "lanes": ["BOT"]},
        {"name": "Udyr", "lanes": ["JG"]},
        {"name": "Urgot", "lanes": ["TOP"]},
        {"name": "Varus", "lanes": ["BOT"]},
        {"name": "Vayne", "lanes": ["TOP", "BOT"]},
        {"name": "Veigar", "lanes": ["MID"]},
        {"name": "Vel'Koz", "lanes": ["MID", "SUP"]},
        {"name": "Vex", "lanes": ["MID"]},
        {"name": "Vi", "lanes": ["JG"]},
        {"name": "Viego", "lanes": ["JG"]},
        {"name": "Viktor", "lanes": ["MID"]},
        {"name": "Vladimir", "lanes": ["TOP", "MID"]},
        {"name": "Volibear", "lanes": ["TOP", "JG"]},
        {"name": "Warwick", "lanes": ["JG"]},
        {"name": "Wukong", "lanes": ["TOP"]},
        {"name": "Xayah", "lanes": ["BOT"]},
        {"name": "Xerath", "lanes": ["MID", "SUP"]},
        {"name": "Xin Zhao", "lanes": ["JG"]},
        {"name": "Yasuo", "lanes": ["TOP", "MID", "BOT"]},
        {"name": "Yone", "lanes": []},
        {"name": "Yorick", "lanes": ["TOP"]},
        {"name": "Yuumi", "lanes": ["SUP"]},
        {"name": "Zac", "lanes": ["JG"]},
        {"name": "Zed", "lanes": ["MID"]},
        {"name": "Zeri", "lanes": ["BOT"]},
        {"name": "Ziggs", "lanes": ["MID"]},
        {"name": "Zilean", "lanes": ["SUP"]},
        {"name": "Zoe", "lanes": ["MID"]},
        {"name": "Zyra", "lanes": ["SUP"]},
    ]


def get_default_champion_names():
    return [
        "Aatrox",
        "Ahri",
        "Akali",
        "Akshan",
        "Alistar",
        "Amumu",
        "Anivia",
        "Annie",
        "Aphelios",
        "Ashe",
        "Aurelion Sol",
        "Azir",
        "Bard",
        "Bel'Veth",
        "Blitzcrank",
        "Brand",
        "Braum",
        "Caitlyn",
        "Camille",
        "Cassiopeia",
        "Cho'Gath",
        "Corki",
        "Darius",
        "Diana",
        "Dr. Mundo",
        "Draven",
        "Ekko",
        "Elise",
        "Evelynn",
        "Ezreal",
        "Fiddlesticks",
        "Fiora",
        "Fizz",
        "Galio",
        "Gangplank",
        "Garen",
        "Gnar",
        "Gragas",
        "Graves",
        "Gwen",
        "Hecarim",
        "Heimerdinger",
        "Illaoi",
        "Irelia",
        "Ivern",
        "Janna",
        "Jarvan IV",
        "Jax",
        "Jayce",
        "Jhin",
        "Jinx",
        "K'Sante",
        "Kai'Sa",
        "Kalista",
        "Karma",
        "Karthus",
        "Kassadin",
        "Katarina",
        "Kayle",
        "Kayn",
        "Kennen",
        "Kha'Zix",
        "Kindred",
        "Kled",
        "Kog'Maw",
        "LeBlanc",
        "Lee Sin",
        "Leona",
        "Lillia",
        "Lissandra",
        "Lucian",
        "Lulu",
        "Lux",
        "Malphite",
        "Malzahar",
        "Maokai",
        "Master Yi",
        "Miss Fortune",
        "Mordekaiser",
        "Morgana",
        "Nami",
        "Nasus",
        "Nautilus",
        "Neeko",
        "Nidalee",
        "Nilah",
        "Nocturne",
        "Nunu & Willump",
        "Olaf",
        "Orianna",
        "Ornn",
        "Pantheon",
        "Poppy",
        "Pyke",
        "Qiyana",
        "Quinn",
        "Rakan",
        "Rammus",
        "Rek'Sai",
        "Rell",
        "Renata Glasc",
        "Renekton",
        "Rengar",
        "Riven",
        "Rumble",
        "Ryze",
        "Samira",
        "Sejuani",
        "Senna",
        "Seraphine",
        "Sett",
        "Shaco",
        "Shen",
        "Shyvana",
        "Singed",
        "Sion",
        "Sivir",
        "Skarner",
        "Sona",
        "Soraka",
        "Swain",
        "Sylas",
        "Syndra",
        "Tahm Kench",
        "Taliyah",
        "Talon",
        "Taric",
        "Teemo",
        "Thresh",
        "Tristana",
        "Trundle",
        "Tryndamere",
        "Twisted Fate",
        "Twitch",
        "Udyr",
        "Urgot",
        "Varus",
        "Vayne",
        "Veigar",
        "Vel'Koz",
        "Vex",
        "Vi",
        "Viego",
        "Viktor",
        "Vladimir",
        "Volibear",
        "Warwick",
        "Wukong",
        "Xayah",
        "Xerath",
        "Xin Zhao",
        "Yasuo",
        "Yone",
        "Yorick",
        "Yuumi",
        "Zac",
        "Zed",
        "Zeri",
        "Ziggs",
        "Zilean",
        "Zoe",
        "Zyra",
    ]
