#      eSports Manager - free and open source eSports Management game
#      Copyright (C) 2020-2023  Pedrenrique G. Guimarães
#
#      This program is free software: you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation, either version 3 of the License, or
#      (at your option) any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU General Public License for more details.
#
#      You should have received a copy of the GNU General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.


def get_default_team_names() -> list:
    return [
        "A Team",
        "All Stars",
        "Amigos",
        "Avengers",
        "Bannermen",
        "Best of the Best",
        "Bosses",
        "Champions",
        "Crew",
        "Dominators",
        "Dream Team",
        "Elite",
        "Force",
        "Goal Diggers",
        "Heatwave",
        "Hot Shots",
        "Hustle",
        "Icons",
        "Justice League",
        "Legends",
        "Lightning",
        "Maniacs",
        "Masters",
        "Monarchy",
        "Naturals",
        "Ninjas",
        "Outliers",
        "Peak Performers",
        "Power",
        "Rebels",
        "Revolution",
        "Ringmasters",
        "Rule Breakers",
        "Shakedown",
        "Squad",
        "Titans",
        "Tribe",
        "United",
        "Vikings",
        "Warriors",
        "Wolf Pack",
        "Aces",
        "Assassins",
        "Armada",
        "Bandits",
        "Blaze",
        "Brute Force",
        "Chaos",
        "Chosen Ones",
        "Conquerors",
        "Defenders",
        "Empire",
        "Extreme",
        "Fury",
        "Gladiators",
        "High Voltage",
        "Hitmen",
        "Inferno",
        "Intimidators",
        "Kingsmen",
        "Lethal Weapons",
        "Mafia",
        "Matrix",
        "No Fear",
        "Outlaws",
        "Pistols",
        "Pulverizers",
        "Rage",
        "Renegades",
        "Riot",
        "Rumble",
        "Samurais",
        "Stealth",
        "Terminators",
        "Trouble Makers",
        "Unbeatable",
        "Venom",
        "Weapons of Mass Destruction",
        "Wrecking Crew",
        "Adrenaline",
        "Alliance",
        "Arsenal",
        "Badasses",
        "Blitz",
        "Brigade",
        "Calvary",
        "Collective",
        "Dothraki",
        "End Game",
        "Fuego",
        "Guardians",
        "Heathens",
        "Horsepower",
        "Impact",
        "Ironmen",
        "Keep It 100",
        "Magic",
        "Mystery",
        "No Sympathy",
        "Obliterators",
        "Phenomenon",
        "Phoenix",
        "Rampage",
        "Regulators",
        "Rough Necks",
        "Savage Joes",
        "Status Quo",
        "Thrashers",
        "Unstoppable",
        "Vicious",
        "Wild Things",
        "Your Worst Nightmare",
        "A Team Has No Name",
        "We Tried",
        "Enter Team Name Here",
        "No Shame",
        "Mediocrity At Its Best",
        "Savage and Average",
        "Wasted Potential",
        "Best Team Name",
        "We Showed Up",
        "Mandatory Attendance",
        "Boom Shaka Laka",
        "Newbies",
        "Mandatory Fun",
        "Noobs",
        "Lovable and Lazy",
        "Our Uniforms Match",
        "Minimum Wagers",
        "Couch Potatoes",
        "Waiting For Naptime",
        "Creative Team Name",
        "Shoes or Lose",
        "Make Teams Great Again",
        "Another Team Name",
        "Cranky Yankees",
        "Movers and Shakers",
        "Heartbreakers",
        "One More Team Name",
        "2nd Choice of Team Name",
        "Coffee Addicts",
        "Cheers For Beers",
        "Tea Spillers",
        "Boozy Bunch",
        "Will Work For Food",
        "Winos",
        "Always Hungry",
        "All Hungover",
        "Praise Cheeses",
        "Cereal Killers",
        "Snack Attack",
        "Addicted to Cake",
        "Cupcakes",
        "Stud Muffins",
        "No Slice Left Behind",
        "Sugar Babies",
        "Sugar Daddies",
        "0% Risk",
        "100 percent",
        "49ers",
        "76ers",
        "8th Wonders of World",
        "99 percenters",
        "Administration",
        "Admirals",
        "Adrenaline",
        "Advocates",
        "Aeros",
        "Aggies",
        "Aliens",
        "Alliance",
        "Alpha Team",
        "Alphas",
        "Ambassadors",
        "American Patriots",
        "Americans",
        "Angels",
        "Animals",
        "Annihilators",
        "Anteaters",
        "Apocalypse",
        "Archers",
        "Around The Horn",
        "Arrows",
        "Asteroids",
        "Astronomic",
        "Astros",
        "Athletics",
        "Avalanche",
        "Aztecs",
        "Bachelors",
        "Bad Boys",
        "Bad Boys 4 Life",
        "Bad News Bears",
        "Bad to The Bone",
        "Bane of Your Existence",
        "Barbarians",
        "Barnstormers",
        "Barons",
        "Bats",
        "Battle Buddies",
        "Battle Hawks",
        "Bay Bears",
        "Bean Counters",
        "Bearcats",
        "Bears",
        "Beasts",
        "Bees",
        "Belles",
        "Bengals",
        "Berets",
        "Big Bats",
        "Big Horns",
        "Bills",
        "Bisons",
        "Black Knights",
        "Black Panthers",
        "Black Widows",
        "Blackhawks",
        "Blades",
        "Blast",
        "Blasters",
        "Blazers",
        "Blitzkrieg",
        "Blossoms",
        "Blue Angels",
        "Blue Birds",
        "Blue Collars",
        "Blue Jackets",
        "Blue Jays",
        "Blue Whales",
        "Blues",
        "Bobcats",
        "Bolts",
        "Bombers",
        "Bookworms",
        "Boomers",
        "Bots",
        "Boulders",
        "Braves",
        "Brewers",
        "Brewmaster",
        "Broncos",
        "Browns",
        "Bruins",
        "Buccaneers",
        "Bucks",
        "Buffaloes",
        "Builders",
        "Bulldogs",
        "Bulldogs",
        "Bulletproof",
        "Bullets",
        "Bullfighters",
        "Bulls",
        "Butchers",
        "Canucks",
        "Capitals",
        "Captains",
        "Captivators",
        "Cardinals",
        "Cavaliers",
        "Celtics",
        "Challengers",
        "Chameleons",
        "Chaos",
        "Chargers",
        "Chasers",
        "Chiefs",
        "CIA",
        "Circus Animals",
        "Claws",
        "Clippers",
        "Cobras",
        "Code Black",
        "Code Red",
        "Collision Course",
        "Colts",
        "Comets",
        "Compadres",
        "Connected",
        "Cosmos",
        "Cougars",
        "Cowboys",
        "Coyotes",
        "Crafty Crew",
        "Crazy 8\u00e2\u20ac\u2122s",
        "Crunch",
        "Crusaders",
        "Crush",
        "Cubs",
        "Curve",
        "Cyclones",
        "Dangers",
        "Darkside",
        "Deal Makers",
        "Deathwish",
        "Decision-makers",
        "Deep Pockets",
        "Delinquents",
        "Demolition Crew",
        "Desert Storm",
        "Desperados",
        "Destroyers",
        "Devils",
        "Diamondbacks",
        "Diplomats",
        "Divas",
        "Divide and Conquer",
        "Dodgers",
        "Dolphins",
        "Dragons",
        "Dream Crushers",
        "Drifters",
        "Drones",
        "Dropping Bombs",
        "Duchesses",
        "Ducks",
        "Dukes",
        "Dynamix",
        "Dynamo",
        "Dynomite",
        "Eagles",
        "Earthquakes",
        "Eliminators",
        "Empowered",
        "Enforcers",
        "Enigma",
        "Entrepreneurs",
        "Eruption",
        "Eskimos",
        "Esquires",
        "Evolution",
        "Executioners",
        "Expendables",
        "Explorers",
        "Explosion",
        "Exterminators",
        "Fairies",
        "Falcons",
        "Fast And Furious",
        "Felons",
        "Fighters",
        "Fighting Irish",
        "Fire",
        "Fire Starters",
        "Firebirds",
        "Fireflies",
        "Firing Squad",
        "Firm",
        "Fisher Cats",
        "Fixers",
        "Flames",
        "Flash",
        "Flight",
        "Flight Crew",
        "Flyers",
        "Flying Dutchmen",
        "Flying Monkeys",
        "Foundation",
        "Four Horsemen",
        "Foxes",
        "Freaks",
        "Frontline",
        "Full Effect",
        "Full Out",
        "Fusion",
        "G-Force",
        "Galaxy",
        "Gamecocks",
        "Gargoyles",
        "Gatling Guns",
        "Gators",
        "Generals",
        "Gentlemen",
        "Ghost Riders",
        "Ghosts",
        "Giants",
        "Goblins",
        "Godfathers",
        "Gold Rush",
        "Golden Eagles",
        "Gophers",
        "Gorillas",
        "Grave Diggers",
        "Gravity",
        "Greyhounds",
        "Griffins",
        "Grizzlies",
        "Growlers",
        "Gulls",
        "Gunners",
        "Guns for Hire",
        "Hammerheads",
        "Hawkeyes",
        "Hawks",
        "Head Hunters",
        "Heat",
        "Hell\u00e2\u20ac\u2122s Angels",
        "Hellraisers",
        "Herons",
        "High Altitude",
        "High Flyers",
        "High Rollers",
        "Hillbillies",
        "Hit Team",
        "Hitters",
        "Hive",
        "Home Runners",
        "Homers",
        "Homies",
        "Hoodlums",
        "Hooks",
        "Hoosiers",
        "Hornets",
        "Hurricanes",
        "Huskies",
        "Hustlers",
        "Icehogs",
        "Ice Wall",
        "Iconic",
        "In Style",
        "Incredibles",
        "Independence",
        "Indians",
        "Infantry",
        "Influencers",
        "Insurgents",
        "Invaders",
        "Islanders",
        "Jackrabbits",
        "Jaguars",
        "Jalapenos",
        "Jawbreakers",
        "Jayhawks",
        "Jazz",
        "Jets",
        "Jocks",
        "Jokers",
        "Judges",
        "Juiced",
        "Jungle Kings",
        "Justice Bringers",
        "Kangeroos",
        "Kickers",
        "Killer Whales",
        "Kingdom",
        "Kingpins",
        "Kings",
        "Kittens",
        "Knights",
        "Koalas",
        "Kryptonite",
        "Ladies",
        "Lady Killers",
        "Lake Hawks",
        "Lakers",
        "Laser Beams",
        "Leaders",
        "Legacy",
        "Leopards",
        "Life Savers",
        "Lilas",
        "Lions",
        "Lobos",
        "Longhorns",
        "Lords",
        "Lost Boys",
        "Lumberjacks",
        "Mad Bombers",
        "Mad Men",
        "Magicians",
        "Majors",
        "Mammoths",
        "Maple Leafs",
        "Marauders",
        "Mariners",
        "Marines",
        "Marlins",
        "Marshalls",
        "Masons",
        "Matadors",
        "Mavericks",
        "Mean Green",
        "Mean Machine",
        "Men In Black",
        "Men on a Mission",
        "Mercenaries",
        "Mermaids",
        "Meteors",
        "Mets",
        "MI6",
        "Mighty Ducks",
        "Minutemen",
        "Mob",
        "Monarchs",
        "Money Makers",
        "Monsters",
        "Moose",
        "Mountaineers",
        "Mud Dogs",
        "Mud Hens",
        "Musketeers",
        "Mustangs",
        "Nationals",
        "Neck Breakers",
        "Nerds",
        "Nets",
        "Nirvana",
        "No Mercy",
        "No Pain, No Gain",
        "No Rules",
        "No Way Out",
        "Northern Lights",
        "Novastars",
        "Nuggets",
        "Occupiers",
        "Oilers",
        "Olympians",
        "Only Contenders",
        "Orcas",
        "Orediggers",
        "Orioles",
        "Otters",
        "Over Achievers",
        "Owls",
        "Pacers",
        "Packers",
        "Padres",
        "Pandas",
        "Panthers",
        "Patriots",
        "Peacekeepers",
        "Peacocks",
        "Penguins",
        "Perfecto\u00e2\u20ac\u2122s",
        "Phantoms",
        "Phillies",
        "Pilots",
        "Pimps",
        "Pioneers",
        "Piranhas",
        "Pirates",
        "Pistons",
        "Pitbulls",
        "Players",
        "Polar Bears",
        "Power House",
        "Prairie Wolves",
        "Predators",
        "Presidents",
        "Priceless",
        "Princes",
        "Princesses",
        "Prodigies",
        "Professionals",
        "Prophets",
        "Prowlers",
        "Punishers",
        "Puppet Masters",
        "Pups",
        "Pythons",
        "Quake",
        "Quicksilvers",
        "Racers",
        "Radicals",
        "Ragin Cajuns",
        "Raging Bulls",
        "Raiders",
        "RailHawks",
        "Rams",
        "Rangers",
        "Rapids",
        "Raptors",
        "Rattlesnakes",
        "Ravens",
        "Rays",
        "Razorbacks",
        "Reapers",
        "Rebellion",
        "Red Bulls",
        "Red Raiders",
        "Red Rapids",
        "Red Rovers",
        "Red Sox",
        "Red Wings",
        "Redbirds",
        "Redhawks",
        "Reds",
        "Redskins",
        "Republic",
        "Rescue Team",
        "Retrievers",
        "Rhinos",
        "Rhythm",
        "Riders",
        "Ringleaders",
        "Rip Tide",
        "River Cats",
        "River Hounds",
        "River Rats",
        "Rivermen",
        "Robots",
        "Rock Cats",
        "Rock Stars",
        "Rockers",
        "Rocket Launchers",
        "Rocketmen",
        "Rockets",
        "Rockies",
        "Rocks",
        "Roses",
        "Rough Riders",
        "Royals",
        "Royalty",
        "Saboteurs",
        "Sabres",
        "Sailors",
        "Saints",
        "Sand Sharks",
        "Savages",
        "Scappers",
        "Scorpions",
        "Scrappers",
        "Screamin Demons",
        "Sea Dogs",
        "Sea Lions",
        "Seabirds",
        "Seahawks",
        "Security",
        "Senators",
        "Shadows",
        "Shameless",
        "Shapeshifters",
        "Sharks",
        "Sharks in Suits",
        "Sharp Shooters",
        "Shield",
        "Shock and Awe",
        "Shocks",
        "Shoguns",
        "Shooting Stars",
        "Showboats",
        "Showrunners",
        "Sicarios",
        "Sinners",
        "Skull Crushers",
        "Skywalkers",
        "Slam",
        "Slayers",
        "Sledgehammers",
        "Sliders",
        "Sluggers",
        "Snipers",
        "Soldiers",
        "Soul Takers",
        "Sounders",
        "Sounds",
        "Spartans",
        "Special K\u00e2\u20ac\u2122s",
        "Speed Demons",
        "Spider Monkeys",
        "Spiders",
        "Spies",
        "Spurs",
        "Squadron",
        "Stallions",
        "Stampede",
        "Stampeders",
        "Stars",
        "Statesmen",
        "Steelers",
        "Stingrays",
        "Stone Crushers",
        "Storm",
        "Storm Breakers",
        "Storm Chasers",
        "Straight Shooters",
        "Strangers",
        "Strikers",
        "Suits",
        "Sultans",
        "Suns",
        "Super Heroes",
        "Super Humans",
        "Super Sonics",
        "Surf",
        "Swag",
        "Swagger",
        "Sweet Heat",
        "Sweethearts",
        "Take No Prisoners",
        "Tar Heels",
        "Tater Tots",
        "Tech Attack",
        "Terrapins",
        "Terrorizers",
        "Texans",
        "Thunder",
        "Thunder Bolts",
        "Thunderbirds",
        "Tidal Waves",
        "Tide",
        "Tides",
        "Tigers",
        "Timbers",
        "Timberwolves",
        "TKOs",
        "Tomcats",
        "Torches",
        "Toreros",
        "Tornadoes",
        "Toros",
        "Trail Blazers",
        "Trappers",
        "Travelers",
        "Tritons",
        "Trojans",
        "Tsunamis",
        "Turtleheads",
        "Twins",
        "Unicorns",
        "Union",
        "Unknowns",
        "Unlimited",
        "Untouchables",
        "Usual Suspects",
        "Vampires",
        "Vandals",
        "Vaqueros",
        "Veterans",
        "Vigilantes",
        "Viking Raiders",
        "Vipers",
        "Volcanoes",
        "Voyagers",
        "Vultures",
        "Wanderers",
        "War Eagles",
        "Warlocks",
        "Warmongers",
        "Watchers",
        "Waves",
        "Weed Wackers",
        "Whales",
        "Whammers",
        "Whirlwinds",
        "White Collars",
        "White Sox",
        "White Walkers",
        "Whitecaps",
        "Wild",
        "Wildcats",
        "Wildebeests",
        "Witches",
        "Wizards",
        "Wolverines",
        "Wolves",
        "Wombats",
        "Workers Bees",
        "Wraiths",
        "X Men",
        "Yankees",
        "Yellow Jackets",
        "Zeniths",
        "Zephyrs",
        "Zombies",
        "Zoo Animals",
        "Afreeca Freecs",
        "Brion Esports",
        "DAMWON Gaming",
        "DRX",
        "Gen.G Esports",
        "Hanwha Life Esports",
        "KT Rolster",
        "Nongshim RedForce",
        "SANDBOX Gaming",
        "T1",
        "Afreeca Freecs Challengers",
        "Brion Esports Challengers",
        "DAMWON Challengers",
        "DRX Challengers",
        "Gen.G Challengers",
        "Hanwha Life Challengers",
        "KT Rolster Challengers",
        "NS RedForce Challengers",
        "SANDBOX Challengers",
        "T1 Challengers",
        "Bilibili Gaming",
        "EDward Gaming",
        "FunPlus Phoenix",
        "Invictus Gaming",
        "JD Gaming",
        "LGD Gaming",
        "LNG Esports",
        "Oh My God",
        "Rare Atom",
        "Rogue Warriors",
        "Royal Never Give Up",
        "Suning",
        "Team WE",
        "ThunderTalk Gaming",
        "Top Esports",
        "Ultra Prime",
        "Victory Five",
        "Bilibili Gaming Junior",
        "FunPlus Phoenix Blaze",
        "Invictus Gaming Young",
        "Joy Dream",
        "LinGan E-sport",
        "Shu Dai Xiong Gaming",
        "Suning-S",
        "Triumphant Song Gaming",
        "V5 87",
        "100 Thieves",
        "Cloud9",
        "Counter Logic Gaming",
        "Dignitas",
        "Evil Geniuses",
        "FlyQuest",
        "Golden Guardians",
        "Immortals",
        "TSM",
        "Team Liquid",
        "100 Thieves Academy",
        "Cloud9 Academy",
        "CLG Academy",
        "Dignitas Academy",
        "Evil Geniuses Academy",
        "FlyQuest Academy",
        "Golden Guardians Academy",
        "Immortals Academy",
        "TSM Academy",
        "Team Liquid Academy",
        "E-Flix eSports",
        "FURIA Esports",
        "Flamengo Esports",
        "INTZ",
        "KaBuM! e-Sports",
        "LOUD",
        "paiN Gaming",
        "RED Canids",
        "Rensga eSports",
        "Vorax",
        "E-Flix eSports Academy",
        "Furia Esports Academy",
        "Flamengo eSports Academy",
        "INTZ Academy",
        "KaBuM! e-Sports Academy",
        "LOUD Academy",
        "paiN Gaming Academy",
        "RED Academy",
        "Rensga eSports Academy",
        "Vorax Academy",
        "All Knights",
        "Estral Esports",
        "Furious Gaming",
        "Infinity Esports",
        "Isurus",
        "Kaos Latin Gamers",
        "Rainbow7",
        "XTEN Esports",
        "100 Thieves Next",
        "Arctic Gaming Mexico",
        "Australs",
        "Barrage Esports NA",
        "Cloud9 Amateur",
        "Coscu Army",
        "Cream Esports Mexico",
        "Evil Geniuses Prodigies",
        "Maryville University",
        "Rebirth eSports",
        "TSM Amateur",
        "Wildcard Gaming Red",
        "Astralis",
        "Excel Esports",
        "FC Schalke 04 Esports",
        "Fnatic",
        "G2 Esports",
        "MAD Lions",
        "Misfits Gaming",
        "Rogue",
        "SK Gaming",
        "Team Vitality",
        "AGO ROGUE",
        "Astralis Talent",
        "BT Excel",
        "FC Schalke 04 Evolution",
        "Fnatic Rising",
        "G2 Arctic",
        "MAD Lions Madrid",
        "Misfits Premier",
        "SK Gaming Prime",
        "Vitality.Bee",
        "1907 Fenerbah\u00c3\u00a7e Esports",
        "5 Ronin",
        "Be\u00c5\u0178ikta\u00c5\u0178 Esports",
        "Dark Passage",
        "Galakticos",
        "Galatasaray Esports",
        "NASR eSports",
        "SuperMassive Esports",
        "Team AURORA",
        "\u00c4\u00b0stanbul Wildcats",
        "1907 Fenerbah\u00c3\u00a7e Academy",
        "5 Ronin Academy",
        "Be\u00c5\u0178ikta\u00c5\u0178 Academy",
        "Dark Passage Academy",
        "Galakticos Academy",
        "Galatasaray Academy",
        "NASR eSports Academy",
        "SuperMassive Academy",
        "Team AURORA Academy",
        "BIG",
        "eSuba",
        "EURONICS Gaming",
        "GamersOrigin",
        "LDLC OL",
        "mousesports",
        "Ad Hoc Gaming",
        "K1CK",
        "Team GamerLegion",
        "Vodafone Giants",
        "7more7",
        "ASUS ROG ELITE",
        "Barrage Esports",
        "Crvena zvezda Esports",
        "devils.one",
        "For The Win Esports",
        "LowLandLions",
        "Lunary",
        "Movistar Riders",
        "Sector One",
        "Solary",
        "Suppup eSports",
        "Team Echo Zulu",
        "Team Singularity",
        "Unicorns of Love Sexy Edition",
        "Dynasty",
        "EGN Esports",
        "Enclave",
        "FALKN",
        "IziDream",
        "MnM Gaming",
        "NVision Esports",
        "Nordavind",
        "Outplayed",
        "PSV Esports",
        "RULE",
        "Riddle Esports",
        "Team MCES",
        "Tricked Esport",
        "UCAM Esports Club",
        "WiLD MultiGaming",
        "x25 eSports",
        "Atlando Esports",
        "CR4ZY",
        "Campus Party Sparks",
        "Cream Real Betis",
        "Dusty",
        "E WIE EINFACH E-SPORTS",
        "Godsent",
        "GameWard",
        "Granit Gaming",
        "Greek Regenesis",
        "Intrepid Fox Gaming",
        "KOVA Esports",
        "KV Mechelen Esports",
        "PRIDE",
        "UniQ Esports Club",
        "Warthox",
        "Bulldog Esports",
        "Five Kings",
        "Hybrid Esports",
        "Iron Wolves",
        "Kenty",
        "mCon esports Rotterdam",
        "mYinsanity",
        "Munster Rugby Academy",
        "Munster Rugby Gaming",
        "Nordavind Academy",
        "OFFSET Esports",
        "PENTA 1860",
        "PIGSPORTS",
        "Racoon",
        "S2V Esports",
        "SAMCLAN Esports Club",
        "SINNERS Esports",
        "Team Oplon",
        "Team Phantasma",
        "Team THRLL",
        "Tony Parker Adequat Academy",
        "Zero Tenacity",
        "Alpha Esports",
        "BOOM Esports",
        "Berjaya Dragons",
        "Beyond Gaming",
        "Hong Kong Attitude",
        "Impunity",
        "J Team",
        "Liyab Esports",
        "Machi Esports",
        "PSG Talon",
        "AXIZ",
        "Burning Core",
        "Crest Gaming Act",
        "DetonatioN FocusMe",
        "Fukuoka SoftBank HAWKS",
        "Rascal Jester",
        "Sengoku Gaming",
        "V3 Esports",
        "Burst The Sky Esports",
        "CERBERUS Esports",
        "GAM Esports",
        "Luxury Esports",
        "Saigon Buffalo",
        "Team Flash",
        "Team Secret",
        "Chiefs Esports Club",
        "Dire Wolves",
        "Gravitas",
        "Legacy Esports",
        "MAMMOTH",
        "ORDER",
        "PEACE",
        "Pentanet.GG",
        "CTRL PLAY",
        "CrowCrowd",
        "Dragon Army",
        "One Breath Gaming",
        "RoX",
        "Unicorns Of Love",
        "Vega Squadron"
    ]
